import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './component/NavBar'
import Bicchi from './component/Bicchi'
import Contact from './component/contact'
import Icon from './component/Icon'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
     
        {children}</body>
        <Contact/>
    </html>
  )
}
